### PR TITLE
Swagger Integration Docs and Example project

### PR DESCRIPTION
**Pull request by mbuhot**
As discussed in #15, this PR adds a section to the `README` describing the usage of the `SwaggerSlateMarkdownWriter` module.

I've added an example application that exercises the end-to-end pipeline:

* Generate a swagger file using `phoenix_swagger`
* Generate markdown with `bureaucrat` and `SwaggerSlateMarkdownWriter`
* Generate HTML from markdown with `slate`
* Serve generated HTML from phoenix application 

While implementing the sample application I found a bug that was preventing complex example parameters from being rendered in the markdown, which is now fixed.

@arnodirlam / @OpakAlex feedback much appreciated!

### CODE REVIEW

**Comment by OpakAlex** [comment]
@mbuhot i think we can use just docker image, and add all example app into image, or we can not?

**Comment by OpakAlex** [comment]
@arnodirlam what you think?

**Comment by arnodirlam** [comment]
Looks very good to me! 👍 

If we add it to the main repo, we also have to take care that it stays up-to-date, e.g. when a new `phoenix` or `phoenix_swagger` version comes out, or when `bureaucrat` is changed ;) I'll add an example app with channels documentation (separate PR), so I'll have to maintain that and you maintain this, okay @mbuhot? ;)

@OpakAlex Honestly, I think a docker image is not that suitable. As plain file storage of the example app it's overkill, and for running an actual Elixir app (with phoenix) in it, it'd need to be packaged (e.g. by distillery). Or maybe I misunderstood? :)

**Comment by mbuhot** [comment]
@arnodirlam Yes, this example app should make things easier for me maintain. It's much simpler than running all the tests for my production application :D

@OpakAlex I think a docker image would be complementary. We'd still need to manage the source code of the example app in a git repo somewhere along with the Dockerfile used to build the image.

**Comment by OpakAlex** [comment]
@mbuhot ok, i am agree. I think we can merge it, @arnodirlam can you merge?

**Pull request merged**
